// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-YsA54cuCX24_NF3SjdYIqtkA9CDB2-k',
    appId: '1:83659478868:web:7d8aa44936eb35151e5ac1',
    messagingSenderId: '83659478868',
    projectId: 'hawahawa-weather-app-46865',
    authDomain: 'hawahawa-weather-app-46865.firebaseapp.com',
    storageBucket: 'hawahawa-weather-app-46865.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRTcZWRG3z-q06hPivm88TBg_SARSlI6o',
    appId: '1:83659478868:android:9be4d2facdba0a231e5ac1',
    messagingSenderId: '83659478868',
    projectId: 'hawahawa-weather-app-46865',
    storageBucket: 'hawahawa-weather-app-46865.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBHkzygwrryFWgSaDtHuX2YOncmQ4OpPU',
    appId: '1:83659478868:ios:a0a63d7b961d91cc1e5ac1',
    messagingSenderId: '83659478868',
    projectId: 'hawahawa-weather-app-46865',
    storageBucket: 'hawahawa-weather-app-46865.firebasestorage.app',
    iosBundleId: 'com.example.hawahawa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBHkzygwrryFWgSaDtHuX2YOncmQ4OpPU',
    appId: '1:83659478868:ios:a0a63d7b961d91cc1e5ac1',
    messagingSenderId: '83659478868',
    projectId: 'hawahawa-weather-app-46865',
    storageBucket: 'hawahawa-weather-app-46865.firebasestorage.app',
    iosBundleId: 'com.example.hawahawa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-YsA54cuCX24_NF3SjdYIqtkA9CDB2-k',
    appId: '1:83659478868:web:e0b80e0ef5951a5c1e5ac1',
    messagingSenderId: '83659478868',
    projectId: 'hawahawa-weather-app-46865',
    authDomain: 'hawahawa-weather-app-46865.firebaseapp.com',
    storageBucket: 'hawahawa-weather-app-46865.firebasestorage.app',
  );
}
